# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Python image
FROM python:3.12-slim AS base

# Set the working directory
WORKDIR /app

# Install dependencies
COPY pyproject.toml uv.lock ./
RUN --mount=type=cache,target=/root/.cache pip install uvicorn \
    && pip install --no-cache-dir -r <(pipenv lock -r) \
    && pip install --no-cache-dir -r <(pipenv lock -r --dev)

# Copy the source code
COPY research_mcp /app/research_mcp
COPY server.py /app/server.py

# Copy the .env file if you want to build it directly into the image
# COPY .env /app/.env

# Set environment variables (can be overridden with a mounted .env file)
ENV NOTION_TOKEN=your_notion_token_here
ENV NOTION_ROOT_DATABASE_ID=your_database_id_here

# Expose the port if necessary
EXPOSE 8000

# Entrypoint to run the server
ENTRYPOINT ["uvicorn", "research_mcp.server:app", "--host", "0.0.0.0", "--port", "8000"]
